---
title: "St. Olaf 12/1"
author: "Ben Wagner"
date: "12/7/2021"
output: html_document
---

```{r, error=FALSE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(rsconnect)
library(lubridate)
library(sportyR)
library(png)
library(patchwork)

StOlaf <- read.csv("C:\\Users\\littl\\OneDrive\\Documents\\Advanced Data Sci\\21-22MacBasketball\\St. Olaf\\21-22 Mac Basketball - St. Olaf.csv")
StMarys<- read.csv("C:\\Users\\littl\\OneDrive\\Documents\\Advanced Data Sci\\21-22MacBasketball\\St. Marys\\21-22 Mac Basketball - St. Mary's.csv")
roster <- read.csv("C:\\Users\\littl\\OneDrive\\Documents\\Advanced Data Sci\\21-22MacBasketball\\21-22 Mac Basketball - Mac Roster.csv")
shot_zone_xy <- read.csv("C:\\Users\\littl\\OneDrive\\Documents\\Advanced Data Sci\\21-22MacBasketball\\21-22 Mac Basketball - Shot Chart.csv")
```


```{r Mac Basketball theme for Plots}

#theme
MacBBall_theme <- theme(
  #titles
  plot.title=element_text(hjust=0.5, size=14, color="#283375"),
  plot.title.position = "plot",
  plot.caption=element_text(size=8, color="#283375", hjust=0.5),
  plot.caption.position = "plot",
  plot.subtitle = element_text(color = "#283375"),

  #background
  panel.border=element_blank(),
  panel.background = element_rect(fill = "#cfb59b"),
  plot.background = element_rect(fill = "#cfb59b"),
  plot.margin=ggplot2::margin(0.5, 0.5, 0.5, 0.5, "in"),
  #axes
  axis.ticks.length=unit(0.15, "cm"),
  axis.line =element_line(colour = "#d97716", 
                      size = 1, linetype = "solid"),
  axis.text = element_text(size=6, color="#283375"),
  #no legend
  legend.position = "none")

Mac_logo <-readPNG("C:\\Users\\littl\\OneDrive\\Documents\\Advanced Data Sci\\21-22MacBasketball\\Mac logo.png", native = TRUE)
```


```{r}
StOlaf %>% 
  filter(Team == "H") %>% 
  filter(Zone!=0) %>% 
  mutate(three_pointer = ifelse(Zone<6, 1, 0)) %>%
  mutate(seconds_left= as.numeric(ms(Time))) %>%  
  group_by(Zone) %>%  
  summarize(fga= n(), fgm=sum(Shot.Result), threePm= sum(Zone<6 && Shot.Result==1), eFg=(fgm+(0.5*threePm))/fga) %>%   
  ggplot(aes(Zone,eFg))+
  geom_col(fill= "#d97716")+
  geom_text(aes(label=fga))+
  scale_x_continuous(breaks=1:15)+
  labs(title= "Effective Field Goal Percentage for each of the Shot Zones",
       x="Zone",
       y="eFg %",
       caption="Ben Wagner | Data: Macalester Men's Basketball ")+
  MacBBall_theme+
  inset_element(p = Mac_logo,
                left = 0.1,
                bottom = 0.66,
                right = 0.25,
                top = 0.95)

  
```


```{r}
StOlaf %>% 
  filter(Team == "H") %>%
  inner_join(roster) %>% 
  filter(Zone!=0) %>% 
  mutate(three_pointer = ifelse(Zone<6, 1, 0)) %>%
  mutate(two_pointer = ifelse(Zone>6, 1, 0)) %>%
  group_by(Name, Zone) %>% 
  summarize(two_pointers= sum(two_pointer), three_pointers= sum(three_pointer), shots_made= sum(Shot.Result), shots_taken= two_pointers+three_pointers, fg=shots_made/shots_taken) %>%  
  ggplot(aes(x=Zone, y=fg))+
  geom_col(fill= "#d97716")+
  facet_wrap(vars(Name), scales = "free")+
  scale_x_continuous(breaks=1:15)+
  labs(title= "Field Goal Percentage for Each Player in the Shot Zones",
       x="Zone",
       y="Fg %",
       caption="Ben Wagner | Data: Macalester Men's Basketball ")+
  MacBBall_theme
  
  
```


```{r}
heat_map <-StOlaf %>% 
  filter(Team == "H") %>% 
  filter(Zone!=0) %>% 
  mutate(three_pointer = ifelse(Zone<6, 1, 0)) %>%
  mutate(seconds_left= as.numeric(ms(Time))) %>%  
  group_by(Zone) %>%  
  summarize(fga= n(), fgm=sum(Shot.Result), threePm= sum(Zone<6 && Shot.Result==1), eFg=(fgm+(0.5*threePm))/fga) %>% 
  left_join(shot_zone_xy, by =c("Zone" = "Zone"))  


Mac_court = geom_basketball('ncaa', full_surf = FALSE, rotate = TRUE,
                 court_apron_color = '#283375',
                 amateur_painted_area_color = '#283375')
  
Mac_court+
  geom_point(data = heat_map, aes(x, y, color=eFg), size= 10)+
  geom_text(data= heat_map, aes(x,y, label=Zone))+
  labs(title= "Mac Shooting Heat Map vs. St. Olaf",
       caption="Ben Wagner | Data: Macalester Men's Basketball ")+
  scale_color_continuous(low = "red", high = "green")+
  theme(plot.title=element_text(hjust=0.5, size=14, color="#283375"),
  plot.title.position = "plot")
```
```{r}
past_two_games <- rbind(StOlaf, StMarys)
heat_map2 <-past_two_games %>%
  filter(Team == "A") %>% 
  filter(Zone!=0) %>% 
  mutate(three_pointer = ifelse(Zone<6, 1, 0)) %>%
  mutate(seconds_left= as.numeric(ms(Time))) %>%  
  group_by(Zone) %>%  
  summarize(fga= n(), fgm=sum(Shot.Result), threePm= sum(Zone<6 && Shot.Result==1), eFg=(fgm+(0.5*threePm))/fga) %>% 
  left_join(shot_zone_xy, by =c("Zone" = "Zone"))  


Mac_court = geom_basketball('ncaa', full_surf = FALSE, rotate = TRUE,
                 court_apron_color = '#283375',
                 amateur_painted_area_color = '#283375')
  
Mac_court+
  geom_point(data = heat_map2, aes(x, y, color=eFg), size= 10)+
  geom_text(data= heat_map, aes(x,y, label=Zone))+
  scale_color_continuous(low = "red", high = "green")+
  labs(title= "Mac Opponents Heat Map",
       caption="Ben Wagner | Data: Macalester Men's Basketball ")+
  theme(plot.title=element_text(hjust=0.5, size=14, color="#283375"),
  plot.title.position = "plot")
```
```{r}
past_two_games <- rbind(StOlaf, StMarys)
heat_map3 <-past_two_games %>%
  filter(Team == "H") %>% 
  filter(Zone!=0) %>% 
  mutate(three_pointer = ifelse(Zone<6, 1, 0)) %>%
  mutate(seconds_left= as.numeric(ms(Time))) %>%  
  group_by(Zone) %>%  
  summarize(fga= n(), fgm=sum(Shot.Result), threePm= sum(Zone<6 && Shot.Result==1), eFg=(fgm+(0.5*threePm))/fga) %>% 
  left_join(shot_zone_xy, by =c("Zone" = "Zone"))  


Mac_court = geom_basketball('ncaa', full_surf = FALSE, rotate = TRUE,
                 court_apron_color = '#283375',
                 amateur_painted_area_color = '#283375')
  
Mac_court+
  geom_point(data = heat_map3, aes(x, y, color=eFg), size= 10)+
  geom_text(data= heat_map, aes(x,y, label=Zone))+
  labs(title= "Mac Opponents Heat Map",
       caption="Ben Wagner | Data: Macalester Men's Basketball ")+
  scale_color_continuous(low = "red", high = "green")+
  theme(plot.title=element_text(hjust=0.5, size=14, color="#283375"),
  plot.title.position = "plot")
```

